name: dotnet package

"on":
  push:
    branches:
      - master

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions for Discord
        run: |
          MESSAGE=${{github.event.head_commit.message}}
          curl -H "Content-Type: application/json" -X POST -d '{"username": "test", "content": ${{github.event.head_commit.message}}}' ${{ secrets.DISCORD_WEBHOOK }}
