name: dotnet package

"on":
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions for Discord
        run: |
          curl  ${{ secrets.DISCORD_WEBHOOK }} -H "Content-Type: application/json" -X POST -d '{"username": "isucon", "content": "${{github.event.head_commit.message}}"}'
