name: dotnet package

"on":
  push:
    branches:
      - master

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions for Discord
        uses: Ilshidur/action-discord@0.3.2
